version: "3.8"

services:
  devcontainer:
    container_name: devcontainer
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
